added ref_fasta, prefix, exclude_pg, template_coordinate, and verbosi…
NZ-MRDP/q2-samtools pull request #5
Opened 2023-08-30 20:18 UTC by mchenaux

…ty flags

2023-08-30 21:39 UTC, HenziKou commented on q2_samtools/plugin_setup.py
> +from q2_types.feature_data import FeatureData, RNASequence, Sequence
Remove unused import `RNASequence`

2023-08-30 21:39 UTC, HenziKou commented on q2_samtools/_samtools.py
> +    RNASequencesDirectoryFormat,
Remove unused imports `DNASequencesDirectoryFormat` and `RNASequencesDirectoryFormat`

2023-08-30 21:39 UTC, HenziKou commented on q2_samtools/_samtools.py
> +            str(prefix),
What will happen if we pass the `-T` flag with the default value set as an empty string? Will samtools throw an error? If an error is thrown then this needs to be moved into its own conditional block.

2023-08-31 17:41 UTC, mchenaux commented on q2_samtools/_samtools.py
> +            str(prefix),
Ok, I think I need some help figuring out the desired behavior here.

2023-08-31 18:44 UTC, HenziKou requested changes

2023-08-31 18:44 UTC, HenziKou commented on q2_samtools/_samtools.py
>              cmd.extend(["-t", tag_sort])
We should probably wrap the arguments for prefix and tag_sort in a string class, e.g. `str(prefix)`

2023-08-31 20:09 UTC, HenziKou approved these changes

2023-08-31 20:10 UTC, merged