Faidx
NZ-MRDP/q2-samtools pull request #6
Opened 2023-09-14 22:09 UTC by mchenaux

2023-09-14 22:11 UTC, mchenaux commented
There are actually two functions hidden in faidx: 1. extraction of part of a fasta, including reformatting using an index and region file as input and 2. indexing. Should these two functions be separated?

2023-09-15 18:39 UTC, HenziKou requested changes

2023-09-15 18:39 UTC, HenziKou commented on q2_samtools/__init__.py
> +__all__ = ["sort", "faidx"]
This list doesn't include the two new functions.

2023-09-15 18:39 UTC, HenziKou commented on q2_samtools/_samtools.py
> +    DNASequencesDirectoryFormat,
Remove unused import.

2023-09-15 18:39 UTC, HenziKou commented on q2_samtools/_samtools.py
> +from q2_types.metadata import ImmutableMetadataFormat
Remove unused import.

2023-09-15 18:39 UTC, HenziKou commented on q2_samtools/_samtools.py
> +    input_fai: SamtoolsIndexFileFormat,
Are these two input files optional?

2023-09-15 18:39 UTC, HenziKou commented on q2_samtools/__init__.py
We probably also need to import the new types we've defined in `_type.py` and add those to our `__all__` list, e.g. https://github.com/NZ-MRDP/q2-bowtie2/blob/main/q2_bowtie2/__init__.py.

2023-09-15 18:39 UTC, HenziKou commented on q2_samtools/plugin_setup.py
> +from q2_types.metadata import ImmutableMetadata
Remove unused imports.

2023-09-15 18:39 UTC, HenziKou commented on q2_samtools/plugin_setup.py
I think you can remove all the `# type: ignore`

2023-09-15 18:39 UTC, HenziKou commented on q2_samtools/plugin_setup.py
> +    name="samtools qiime plugin",
We should update the name sections for each method, e.g. `name='Denoise and dereplicate single-end sequences'` found in q2_dada2.denoise_single

2023-09-15 19:02 UTC, mchenaux commented on q2_samtools/__init__.py
> +__all__ = ["sort", "faidx"]
So, I wasn't sure about that, actually. Are these supposed to be the functions I'm defining or the samtools function? because both extract_fasta_subsequence and index_fasta are calling faidx.

2023-09-15 20:55 UTC, HenziKou commented on q2_samtools/_samtools.py
> +    input_fai: SamtoolsIndexFileFormat,
If they're not optional then we don't need to place them in if statements (lines 91-94) and they can go directly into the `cmd` list.

2023-09-15 20:55 UTC, HenziKou commented on q2_samtools/__init__.py
> +__all__ = ["sort", "faidx"]
These are going to be the functions you've defined within your `_samtools.py` file.

2023-09-15 20:58 UTC, HenziKou commented on q2_samtools/_samtools.py
> +        cmd.extend(["--fai-idx", str(input_fai)])
We can move these into the `cmd` list above since these arguments are not optional.

2023-09-15 22:30 UTC, HenziKou approved these changes

2023-09-15 22:30 UTC, merged